name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Imprimir en consola
        run: echo "helloworld, GITHUB ACTIONS"

  test:
    needs: helloworld
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test_FastAPI_imports
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_CREDENTIALS_BASE64: ${{ secrets.FIREBASE_CREDENTIALS_BASE64 }}
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: pytest -v test_database.py
      - name: Run test
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_CREDENTIALS_BASE64: ${{ secrets.FIREBASE_CREDENTIALS_BASE64 }}
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: pytest -v test_database.py

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Railway CLI
        run: curl -sSL https://railway.app/install.sh | sh
      
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          echo "starting deployment..."
          railway up --service "Alquiler.ui"
